// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnRepoIntelStatus } from "./TurnRepoIntelStatus";

export type TurnRepoIntelUpdatedNotification = { threadId: string, turnId: string, status: TurnRepoIntelStatus, summary: string, details: Array<string>, };
